# docker-compose.yml
version: "3.8" # Versión de Docker Compose

services:
  fast_store:
    build:
      context: . # Busca el Dockerfile en el directorio actual
      dockerfile: Dockerfile # Usa el Dockerfile que definimos
    ports:
      - "4321:4321" # Mapea el puerto 4321 del contenedor al 4321 de tu máquina
    volumes:
      - .:/app # Monta el directorio actual de tu proyecto en /app dentro del contenedor
        # Esto es CRUCIAL para que db.d.ts se genere localmente
    environment:
      # Pasa tus variables de entorno de Turso al contenedor
      # Docker Compose puede leer directamente de un archivo .env si lo configuras
      - ASTRO_DB_REMOTE_URL=${ASTRO_DB_REMOTE_URL}
      - ASTRO_DB_APP_TOKEN=${ASTRO_DB_APP_TOKEN}
      # Establece NODE_ENV para un rendimiento óptimo o logs específicos
      - NODE_ENV=development
    command: npx astro dev # Sobrescribe el CMD del Dockerfile para iniciar el servidor de desarrollo
    # Si quieres una shell interactiva para ejecutar comandos db push/seed manualmente:
    # entrypoint: ["bash"]
    # tty: true
    # stdin_open: true
